Repository DdNnTt/Chingu-Backend, pull requests merged in 2025-03, with the labels that each got.

#8 회원 탈퇴 기능 구현
  src/main/java/com/chingubackend/controller/UserController.java
  src/main/java/com/chingubackend/dto/request/UserRequest.java
  src/main/java/com/chingubackend/repository/UserRepository.java
  src/main/java/com/chingubackend/service/UserService.java
Labels: Feat, Priority:high, Rename

#9 개인 스케줄 기능 추가
  src/main/java/com/chingubackend/controller/ScheduleController.java
  src/main/java/com/chingubackend/dto/request/ScheduleRequest.java
  src/main/java/com/chingubackend/entity/Schedule.java
  src/main/java/com/chingubackend/repository/ScheduleRepository.java
  src/main/java/com/chingubackend/service/ScheduleService.java
Labels: Feat, Priority:high, Rename

#11 아이디, 닉네임 중복확인 API 추가
  src/main/java/com/chingubackend/controller/UserController.java
  src/main/java/com/chingubackend/service/UserService.java
Labels: Feat, Priority:medium

#12 Fix: Merge 후 발생한 에러 수정
  src/main/java/com/chingubackend/controller/UserController.java
  src/main/java/com/chingubackend/service/UserService.java
Labels: Fix, Priority:high

#13 Docs: PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs, Priority:high

#16 Feature/users
  build.gradle
  src/main/java/com/chingubackend/config/.gitkeep
  src/main/java/com/chingubackend/config/KeyGenerator.java
  src/main/java/com/chingubackend/config/SecurityConfig.java
  src/main/java/com/chingubackend/controller/.gitkeep
  src/main/java/com/chingubackend/controller/LoginController.java
  src/main/java/com/chingubackend/controller/UserController.java
  src/main/java/com/chingubackend/dto/request/.gitkeep
  src/main/java/com/chingubackend/dto/request/LoginRequest.java
  src/main/java/com/chingubackend/dto/response/.gitkeep
  src/main/java/com/chingubackend/dto/response/LoginResponse.java
  src/main/java/com/chingubackend/entity/.gitkeep
  src/main/java/com/chingubackend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/chingubackend/jwt/JwtUtil.java
  src/main/java/com/chingubackend/repository/.gitkeep
  src/main/java/com/chingubackend/repository/UserRepository.java
  src/main/java/com/chingubackend/security/.gitkeep
  src/main/java/com/chingubackend/security/CustomUserDetailsService.java
  src/main/java/com/chingubackend/security/SecurityConfig.java
  src/main/java/com/chingubackend/service/.gitkeep
  src/main/java/com/chingubackend/service/UserService.java
  src/main/resources/application.properties
Labels: Feat, Priority:high, Refoctor

#18 Feature/myhome friend
  src/main/java/com/chingubackend/controller/FriendController.java
  src/main/java/com/chingubackend/dto/request/FriendRequest.java
  src/main/java/com/chingubackend/entity/Friend.java
  src/main/java/com/chingubackend/entity/FriendshipScore.java
  src/main/java/com/chingubackend/model/RequestStatus.java
  src/main/java/com/chingubackend/repository/FriendRepository.java
  src/main/java/com/chingubackend/repository/FriendshipScoreRepository.java
  src/main/java/com/chingubackend/service/FriendService.java
Labels: Cleanup, Feat, Priority:high, Back-end

#20 Feature/user search
  src/main/java/com/chingubackend/controller/UserController.java
  src/main/java/com/chingubackend/dto/response/UserResponse.java
  src/main/java/com/chingubackend/repository/UserRepository.java
  src/main/java/com/chingubackend/service/UserService.java
Labels: Feat

#22 Feature/email check
  build.gradle
  src/main/java/com/chingubackend/config/RedisConfig.java
  src/main/java/com/chingubackend/config/SecurityConfig.java
  src/main/java/com/chingubackend/controller/AuthController.java
  src/main/java/com/chingubackend/service/EmailService.java
  src/main/java/com/chingubackend/service/MailService.java
  src/main/java/com/chingubackend/service/UserService.java
  src/main/resources/application.properties
Labels: Feat, Priority:high
