Repository DdNnTt/Chingu-Backend, pull requests merged in 2025-04, with the labels that each got.

#24 Feat/jwt user pk
  src/main/java/com/chingubackend/controller/LoginController.java
  src/main/java/com/chingubackend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/chingubackend/jwt/JwtUtil.java
Labels: Feat, Refoctor

#26 Feat/mypage
  src/main/java/com/chingubackend/controller/UserController.java
  src/main/java/com/chingubackend/dto/request/DeleteUserRequest.java
  src/main/java/com/chingubackend/dto/request/UserUpdateRequest.java
  src/main/java/com/chingubackend/service/UserService.java
Labels: Feat, Priority:high, Refoctor

#30 GitHub Actions 설정 및 EC2 배포 스크립트 추가
  .github/workflows/deploy.yml
  start.sh
Labels: Chore, Fix, Setting

#32 Feature/friend group
  src/main/java/com/chingubackend/controller/FriendController.java
  src/main/java/com/chingubackend/controller/GroupController.java
  src/main/java/com/chingubackend/controller/ScheduleController.java
  src/main/java/com/chingubackend/dto/request/GroupRequest.java
  src/main/java/com/chingubackend/dto/response/GroupResponse.java
  src/main/java/com/chingubackend/entity/Group.java
  src/main/java/com/chingubackend/repository/GroupRepository.java
  src/main/java/com/chingubackend/service/GroupService.java
Labels: Docs, Feat

#34 Feat/group
  src/main/java/com/chingubackend/config/SecurityConfig.java
  src/main/java/com/chingubackend/controller/GroupController.java
  src/main/java/com/chingubackend/dto/request/GroupRequest.java
  src/main/java/com/chingubackend/dto/response/GroupDeleteResponse.java
  src/main/java/com/chingubackend/dto/response/GroupResponse.java
  src/main/java/com/chingubackend/entity/Group.java
  src/main/java/com/chingubackend/security/CustomAccessDeniedHandler.java
  src/main/java/com/chingubackend/service/GroupService.java
Labels: Feat, Refoctor

#36 Feat/my groups
  src/main/java/com/chingubackend/controller/GroupController.java
  src/main/java/com/chingubackend/dto/request/GroupInviteRequest.java
  src/main/java/com/chingubackend/dto/request/GroupInviteStatusRequest.java
  src/main/java/com/chingubackend/dto/response/GroupInviteResponse.java
  src/main/java/com/chingubackend/entity/GroupInvite.java
  src/main/java/com/chingubackend/entity/GroupMember.java
  src/main/java/com/chingubackend/repository/GroupInviteRepository.java
  src/main/java/com/chingubackend/repository/GroupMemberRepository.java
  src/main/java/com/chingubackend/service/GroupService.java
Labels: Feat, Fix, Refoctor

#38 refactor/myhome_schedule
  src/main/java/com/chingubackend/controller/ScheduleController.java
  src/main/java/com/chingubackend/dto/request/ScheduleRequest.java
  src/main/java/com/chingubackend/repository/ScheduleRepository.java
  src/main/java/com/chingubackend/service/ScheduleService.java
Labels: Refoctor
